apiVersion: v1
kind: ConfigMap
metadata:
  name: jcmds-mock-dev-config
data:
  db.json: |
    {
     "samples": [],
     "destinations": []
    }
---
apiVersion: v1
kind: Service
metadata:
  name: jcmds-mock-dev-api-svc
  labels:
    app: jcmds-mock-dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: jcmds-mock-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jcmds-mock-dev-api-dep
  labels:
    app: jcmds-mock-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jcmds-mock-dev
  template:
    metadata:
      labels:
        app: jcmds-mock-dev
    spec:
      containers:
      - name: jcmds-mock-dev
        image: jcmds/jsonserver
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: jcmds-mock-dev-volume
          mountPath: /data
      volumes:
      - name: jcmds-mock-dev-volume
        configMap:
          name: jcmds-mock-dev-config
